@startuml
title GridStack UML Diagram v1.2

class GridStackWidget {
    x
    y
    w
    h
    id
    content 
    // ... many others
}

class GridStackNode extends GridStackWidget, GridStackWidgetExt {
    el?: GridItemHTMLElement
    grid
    subGrid
}

class GridStackWidgetExt extends GridStackWidget {
    kind: Component 
    kindEditor: Component
}

interface GridStackElement {}

class HTMLElement {}

class GridItemHTMLElement extends HTMLElement {
    gridstackNode?: GridStackNode
}

class Grid {
    nodes: GridStackNode[]
}

Grid *-- "*" GridStackNode

GridStackNode --> "el" GridItemHTMLElement
GridItemHTMLElement ..> "gridstackNode" GridStackNode
GridStackNode ..> "grid" Grid
'GridStackWidgetExt --> GridStackWidget 
'GridStackNode --|> GridStackWidgetExt

note bottom of GridStackElement
    string | HTMLElement | GridItemHTMLElement
end note

@enduml
